### ISSUE TITLE
fixture 'app_config' not found using fixture engine

### ISSUE THREAD

**Issue by jayvdb** [pytest-dev/pytest-sqlalchemy#1]
After installation, using the `engine` fixture results in fixture 'app_config' not found

```
file /usr/lib/python3.4/site-packages/pytest_sqlalchemy.py, line 25
  @pytest.fixture(scope="module")
  def connection(request, engine):
file /usr/lib/python3.4/site-packages/pytest_sqlalchemy.py, line 6
  @pytest.fixture(scope="module")
  def engine(request, sqlalchemy_connect_url, app_config):
        fixture 'app_config' not found
        available fixtures: connection, capfd, qapp, smtpserver, recwarn, sqlalchemy_connect_url, httpserver, pytestconfig, httpsserver, monkeypatch, tmpdir_factory, qtlog, engine, capsys, qtbot, cache, tmpdir, record_xml_property, transaction, dbsession, cov
        use 'py.test --fixtures [testpath]' for help on them.

```

A simple workaround is to create `conftest.py` with

``` py
import pytest


@pytest.yield_fixture(scope="session")
def app_config():
    yield None
```

Is there a better approach?

**Comment by jayvdb** [comment]
Also, shouldnt this package have a dependency on sqlalchemy ?

**Comment by toirl** [comment]
Hi,
Thanks for the report. 

First: I will fix the app_config issue soon. This option was meant to be used in a larger context providing a ini file with the connection string in the ini. As the app_config should be optiona your workaround is ok.

Second: You are completly right: sqlalchemy should be a dependency. Again I missed this as pytest-sqlalchemy is only used in a larger context which already ha the sqlalchemy dependency.

Thanks!

**Comment by toirl** [comment]
Hi,

With 5de970864cb42377b5dfb6530fd0fdfee8d2c4b1 I implemented a very basic version of the intended functionality of app_config. This should fix this issue.

**Comment by jayvdb** [comment]
Indeed.  Fixed.
Could you release these fixes to pypi?
