### ISSUE TITLE
Multiple databases?

### ISSUE THREAD

**Issue by taybin** [pytest-dev/pytest-sqlalchemy#3]
Is there a way to set this up to support multiple databases simultaneously?  I'm working on a project that has a connection to both a postgresql DB *and* a mysql DB. 🙄

**Comment by codebydant** [comment]
@taybin I think you can use multiple engines for this.

**Comment by odigity** [comment]
The Changelog says multi-db support was added v0.2.  If that's true, perhaps this issue can be closed successfully?
https://github.com/toirl/pytest-sqlalchemy/blob/master/HISTORY.rst

BTW - Being new to SQLAlchemy and just discovering this package, I'm curious if it's still maintained and supports SQLAlchemy v2, which just came out a few months ago.

**Comment by toirl** [comment]
Hey! Thanks for asking. Will close the issue. Regarding the maintenance of this package I must say that this package isn't actively maintained anymore. It wrote it years ago to make testing more easy in my own project.  I was (an still be) happy that it useful to some other people. However I don't spent any time on on this package anymore. Will update the README to point this out. 

I am sorry but can not say if the package will work with v2 of SQLAlchemy. Haven't looked into it yet.
