### ISSUE TITLE
document intended usage of fixtures

### ISSUE THREAD

**Issue by antoine-gallix** [pytest-dev/pytest-sqlalchemy#6]
It's not clear for me how each fixture is supposed to be used. Could you provide examples?

**Comment by toirl** [comment]
Hi, 
Yes you're right. This could be more clear.
I think I can provide some example during next week.

**Comment by toirl** [comment]
Hi,
I am sorry for being late. I updated the README and hope this makes the usage a little bit more clear. There is no special thing on using the fixtures. The fixtures are used as described in the pytest documentation and give access to the SQLAlchemy objects of the same name.

Is this of any help?

**Comment by antoine-gallix** [comment]
Yes, that is helping, thank you!
