### ISSUE TITLE
[Question] does this project supports adding/cleaning dummy data to the database?

### ISSUE THREAD

**Issue by codebydant** [pytest-dev/pytest-sqlalchemy#9]
HI @toirl ,

Thanks for this wonderful tool.

I was wondering if this package could be used to add some dummy data to the database when the test case runs, and then when the test case is done, clean the data from the table in the database.

**Comment by toirl** [comment]
Hi @dtcMLOps. This is not yet supported, as the data is so custom and specific to the tests. However the creation and dropping of database is done on the fly. 

Based on this you should be able to write your on fixtures which does adding and cleaning dummy data into your DB as needed.

**Comment by codebydant** [comment]
Hi @toirl, thanks. Indeed, I have created my own fixtures, and using the package is working as expected.
